steps:
  - command: "./scripts/build-and-push-container.sh cppkin ubuntu1804 $BUILDKITE_BRANCH"
    label: ":ubuntu: 18.04 Docker build cppkin"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 15
    retry:
      automatic: true

  - command: "./scripts/build-and-push-container.sh cppkin ubuntu1904 $BUILDKITE_BRANCH"
    label: ":ubuntu: 19.04 Docker build cppkin"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 15
    retry:
      automatic: true
  
  - command: "./scripts/build-and-push-container.sh cppkin ubuntu2004 $BUILDKITE_BRANCH"
    label: ":ubuntu: 20.04 Docker build cppkin"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 15
    retry:
      automatic: true

  - wait

  - block: "Package version"
    branches: "master"
    prompt: "Input package version"
    fields:
      - text: "Version"
        key: "package-version"
        hint: "Package version for cppkin"

  - wait

  - command: |
      VERSION=$(buildkite-agent meta-data get package-version)
      CID=$(docker run -d registry.devel.b1ops.net/b1automation/cppkin_ubuntu1804:$BUILDKITE_BRANCH ./scripts/generate_deb.sh $VERSION "18.04")
      sleep 5
      docker cp $CID:/cppkin_${VERSION}-ubuntu-18.04_amd64.deb .
      ls
    branches: "master"
    label: ":ubuntu: 18.04 Create cppkin debian package"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 5
    artifact_paths:
      - "*.deb"

  - command: |
      VERSION=$(buildkite-agent meta-data get package-version)
      CID=$(docker run -d registry.devel.b1ops.net/b1automation/cppkin_ubuntu1904:$BUILDKITE_BRANCH ./scripts/generate_deb.sh $VERSION "19.04")
      sleep 5
      docker cp $CID:/cppkin_${VERSION}-ubuntu-19.04_amd64.deb .
      ls
    branches: "master"
    label: ":ubuntu: 19.04 Create cppkin debian package"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 5
    artifact_paths:
      - "*.deb"
  
  - command: |
      VERSION=$(buildkite-agent meta-data get package-version)
      CID=$(docker run -d registry.devel.b1ops.net/b1automation/cppkin_ubuntu2004:$BUILDKITE_BRANCH ./scripts/generate_deb.sh $VERSION "20.04")
      sleep 5
      docker cp $CID:/cppkin_${VERSION}-ubuntu-20.04_amd64.deb .
      ls
    branches: "master"
    label: ":ubuntu: 20.04 Create cppkin debian package"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 5
    artifact_paths:
      - "*.deb"

