steps:
  - command: "./scripts/build-and-push-container.sh cppkin $BUILDKITE_BRANCH"
    label: "Docker build eosio-cppkin"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 15
    retry:
      automatic: true
