steps:
  - command: "./scripts/build-and-push-container.sh cppkin $BUILDKITE_BRANCH"
    label: "Docker build eosio-cppkin"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 15
    retry:
      automatic: true

  - wait

  - block: "Package version"
    branches: "master"
    prompt: "Input package version"
    fields:
      - text: "Version"
        key: "package-version"
        hint: "Package version for cppkin"

  - wait

  - command: |
      VERSION=$(buildkite-agent meta-data get package-version)
      CID=$(docker run -d registry.devel.b1ops.net/b1automation/cppkin:$BUILDKITE_BRANCH ./scripts/generate_deb.sh $VERSION)
      sleep 5
      docker cp $CID:/cppkin_${VERSION}-ubuntu-18.04_amd64.deb .
      ls
    branches: "master"
    label: "Create cppkin debian package"
    agents:
      queue: "automation-eks-docker-builder-fleet"
    timeout: 5
    artifact_paths:
      - "*.deb"

